---
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - fingerprint:
      fields:
        - "flow.id"
        - "netflow.exporter.address"
        - "netflow.exporter.timestamp"
      target_field: "@metadata._id"
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.template.enabled: true
setup.template.type: index
setup.template.name: "filebeat-netflow-%{[agent.version]}"
setup.template.pattern: "filebeat-netflow-%{[agent.version]}-*"
setup.template.overwrite: false
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 1

setup.ilm.enabled: true
setup.ilm.rollover_alias: "filebeat-netflow-%{[agent.version]}"
setup.ilm.pattern: "{now/d}-000001"
setup.ilm.policy_name: "default-filebeat-netflow"
setup.ilm.check_exists: true
setup.ilm.overwrite: false

output.elasticsearch:
  enabled: true
  hosts: ["${ELASTIC_HOST}:${ELASTIC_PORT}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities:
    - "/usr/share/filebeat/certs/ca.crt"
  loadbalance: true
  index: "filebeat-netflow-%{[agent.version]}-%{+yyyy.MM.dd}"
  protocol: https
  ssl.enabled: true

filebeat.inputs:
  - type: netflow
    max_message_size: 10KiB
    host: "0.0.0.0:2055"
    protocols: [v5, v9, ipfix]
    expiration_timeout: 30m
    queue_size: 8192
    detect_sequence_reset: true
    tags: ["filebeat_netflow"]
