---

kind: Component

patches:
  - patch: |-
      ---
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: filebeat-netflow-ds
      spec:
        template:
          spec:
            volumes:
              - name: filebeat-netflow-certs
                secret:
                  secretName: filebeat-netflow-certs
            containers:
              - name: filebeat-netflow
                volumeMounts:
                  - name: filebeat-netflow-certs
                    mountPath: /usr/share/filebeat/certs/
